
export const membersData = [
    {
      "email": "johndoe@gmail.com",
      "username": "johndoe",
      "gender": "male",
      "dateOfBirth": "1990-05-15",
      "name": "John Doe",
      "created": "2025-01-01",
      "lastActive": "2025-01-24",
      "description": "A passionate traveler and photographer.",
      "city": "New York",
      "country": "USA",
      "image": "/images/f1.jpg"
    },
    {
      "email": "janedoe@gmail.com",
      "username": "janedoe",
      "gender": "female",
      "dateOfBirth": "1985-07-22",
      "name": "Jane Doe",
      "created": "2025-01-05",
      "lastActive": "2025-01-23",
      "description": "Lover of books and history.",
      "city": "Los Angeles",
      "country": "USA",
      "image": "/images/f2.jpg"
    },
    {
      "email": "emily_smith@gmail.com",
      "username": "emily_smith",
      "gender": "female",
      "dateOfBirth": "1992-11-03",
      "name": "Emily Smith",
      "created": "2025-01-02",
      "lastActive": "2025-01-21",
      "description": "Coffee enthusiast and yoga practitioner.",
      "city": "London",
      "country": "UK",
      "image": "/images/f3.jpg"
    },
    {
      "email": "mark_jones@gmail.com",
      "username": "mark_jones",
      "gender": "male",
      "dateOfBirth": "1987-03-27",
      "name": "Mark Jones",
      "created": "2025-01-10",
      "lastActive": "2025-01-20",
      "description": "Software engineer and gamer.",
      "city": "Sydney",
      "country": "Australia",
      "image": "/images/f4.jpg"
    },
    {
      "email": "lisa_taylor@gmail.com",
      "username": "lisa_taylor",
      "gender": "female",
      "dateOfBirth": "1995-01-14",
      "name": "Lisa Taylor",
      "created": "2025-01-07",
      "lastActive": "2025-01-19",
      "description": "Fitness coach and foodie.",
      "city": "Toronto",
      "country": "Canada",
      "image": "/images/f5.jpg"
    },
    {
      "email": "alex_lee@gmail.com",
      "username": "alex_lee",
      "gender": "male",
      "dateOfBirth": "1989-09-09",
      "name": "Alex Lee",
      "created": "2025-01-03",
      "lastActive": "2025-01-22",
      "description": "Avid traveler and musician.",
      "city": "Tokyo",
      "country": "Japan",
      "image": "/images/f6.jpg"
    },
    {
      "email": "susan_clark@gmail.com",
      "username": "susan_clark",
      "gender": "female",
      "dateOfBirth": "1980-04-25",
      "name": "Susan Clark",
      "created": "2025-01-12",
      "lastActive": "2025-01-15",
      "description": "Adventure lover and painter.",
      "city": "Berlin",
      "country": "Germany",
      "image": "/images/f7.jpg"
    },
    {
      "email": "robert_wilson@gmail.com",
      "username": "robert_wilson",
      "gender": "male",
      "dateOfBirth": "1994-02-10",
      "name": "Robert Wilson",
      "created": "2025-01-14",
      "lastActive": "2025-01-25",
      "description": "Tech enthusiast and entrepreneur.",
      "city": "San Francisco",
      "country": "USA",
      "image": "/images/f8.jpg"
    },
    {
      "email": "charlotte_davis@gmail.com",
      "username": "charlotte_davis",
      "gender": "female",
      "dateOfBirth": "1993-09-30",
      "name": "Charlotte Davis",
      "created": "2025-01-09",
      "lastActive": "2025-01-18",
      "description": "Art lover and fashionista.",
      "city": "Paris",
      "country": "France",
      "image": "/images/f9.jpg"
    },
    {
      "email": "william_martin@gmail.com",
      "username": "william_martin",
      "gender": "male",
      "dateOfBirth": "1982-11-11",
      "name": "William Martin",
      "created": "2025-01-06",
      "lastActive": "2025-01-17",
      "description": "Fitness enthusiast and nature lover.",
      "city": "Vancouver",
      "country": "Canada",
      "image": "/images/f10.jpg"
    }
]
  