import type { Metadata } from "next";
import "./globals.css";
import Providers from "../components/Providers";
import { auth } from "@/auth";

export const metadata: Metadata = {
    title: "Next Match",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await auth();
    const userId = session?.user?.id || null;

    return (
        <html lang="en">
            <body>
                <Providers userId={userId}>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
